apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-log-output

resources:
- ./../../base
patches:
  - path: deployment.yaml

namePrefix: prod-

images:
- name: log-output-image
  newName: saakbar/log_output
  newTag: v1.0.0
