apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-the-project

resources:
- ./../../base/app
- ./../../base/backend
- ./../../base/broadcaster

namePrefix: staging-

images:
- name: broadcaster-image
  newName: saakbar/broadcaster
  newTag: v1
- name: todo-app-image
  newName: saakbar/todo-app
  newTag: v7
- name: todo-backend-image
  newName: saakbar/todo-backend
  newTag: v13
