apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todo-backend/manifests/deployments.yaml
- todo-backend/manifests/service.yaml
- todo-app/manifests/deployment.yaml
- todo-app/manifests/service.yaml
- broadcaster/manifests/deployment.yaml
- broadcaster/manifests/service.yaml
  # - manifests/nats.yaml

images:
- name: broadcaster-image
  newName: saakbar/broadcaster
  newTag: 5a646ef619d883dc9f5e8b5d1902e00b0e6d6d32
- name: todo-app-image
  newName: saakbar/todo-app
  newTag: 5a646ef619d883dc9f5e8b5d1902e00b0e6d6d32
- name: todo-backend-image
  newName: saakbar/todo-backend
  newTag: 5a646ef619d883dc9f5e8b5d1902e00b0e6d6d32
