apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todo-backend/manifests/deployments.yaml
- todo-backend/manifests/service.yaml
- todo-app/manifests/deployment.yaml
- todo-app/manifests/service.yaml
- broadcaster/manifests/deployment.yaml
- broadcaster/manifests/service.yaml
  # - manifests/nats.yaml

images:
- name: broadcaster-image
  newName: saakbar/broadcaster
  newTag: 14c50cd81aad719e0d15018d537a4f22fd9ff139
- name: todo-app-image
  newName: saakbar/todo-app
  newTag: 14c50cd81aad719e0d15018d537a4f22fd9ff139
- name: todo-backend-image
  newName: saakbar/todo-backend
  newTag: 14c50cd81aad719e0d15018d537a4f22fd9ff139
