apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todo-backend/manifests/deployments.yaml
- todo-backend/manifests/service.yaml
- todo-app/manifests/deployment.yaml
- todo-app/manifests/service.yaml
- broadcaster/manifests/deployment.yaml
- broadcaster/manifests/service.yaml
  # - manifests/nats.yaml

images:
- name: broadcaster-image
  newName: saakbar/broadcaster
  newTag: f77a80406fe6dc335666b5fa81cf77e9ec61200f
- name: todo-app-image
  newName: saakbar/todo-app
  newTag: f77a80406fe6dc335666b5fa81cf77e9ec61200f
- name: todo-backend-image
  newName: saakbar/todo-backend
  newTag: f77a80406fe6dc335666b5fa81cf77e9ec61200f
