apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - todo-backend/manifests/deployments.yaml
  - todo-backend/manifests/service.yaml
  - todo-app/manifests/deployment.yaml
  - todo-app/manifests/service.yaml

images:
  - name: todo-app-image
    newName: us-central1-docker.pkg.dev/PROJECT_ID/app-repo/app
  - name: todo-backend-image
    newName: us-central1-docker.pkg.dev/PROJECT_ID/app-repo/app
