apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todo-backend/manifests/deployments.yaml
- todo-backend/manifests/service.yaml
- todo-app/manifests/deployment.yaml
- todo-app/manifests/service.yaml
- broadcaster/manifests/deployment.yaml
- broadcaster/manifests/service.yaml
  # - manifests/nats.yaml

images:
- name: broadcaster-image
  newName: saakbar/broadcaster
  newTag: e01dfd5f8c8403de7ea13956a8dbb5efd02ad2fb
- name: todo-app-image
  newName: saakbar/todo-app
  newTag: e01dfd5f8c8403de7ea13956a8dbb5efd02ad2fb
- name: todo-backend-image
  newName: saakbar/todo-backend
  newTag: e01dfd5f8c8403de7ea13956a8dbb5efd02ad2fb
