apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - todo-backend/manifests/deployments.yaml
  - todo-backend/manifests/service.yaml
  - todo-app/manifests/deployment.yaml
  - todo-app/manifests/service.yaml