apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-1
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator-1
  template:
    metadata:
      labels:
        app: hashgenerator-1
    spec:
      containers:
        - name: hashgenerator-1
          image: log-output-image
          imagePullPolicy: Always
          env:
            - name: MESSAGE
              value: "hello world"
            - name: PORT
              value: "5001"
            - name: PINGPONG_URL
              value: "http://pingpong-svc:5000/"
            - name: GREETER_URL
              value: "http://greeter-svc:8080/"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-2
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator-2
  template:
    metadata:
      labels:
        app: hashgenerator-2
    spec:
      containers:
        - name: hashgenerator-2
          image: log-output-image
          imagePullPolicy: Always
          env:
            - name: MESSAGE
              value: "hello world"
            - name: PORT
              value: "5001"
            - name: PINGPONG_URL
              value: "http://pingpong-svc:5000/"
            - name: GREETER_URL
              value: "http://greeter-svc:8080/"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10

