apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: pingpong-pvc
          persistentVolumeClaim:
            claimName: pingpong-pvc
      containers:
        - name: hashgenerator
          image: hashgenerator:latest
          imagePullPolicy: Never
          volumeMounts:
          - name: pingpong-pvc
            mountPath: /usr/src