apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hashresponse-httproute
  namespace: exercises
spec:
  parentRefs:
    - name: hashresponse-gateway
  hostnames:
    - "log-output.shujaakbar.com"
  rules:
    - matches:
        - path:
            type: PathPrefix       # <-- changed from Prefix
            value: "/"
      backendRefs:
        - name: hashresponse-svc
          port: 5000
    - matches:
        - path:
            type: PathPrefix       # <-- changed from Prefix
            value: "/pingpong"
      backendRefs:
        - name: pingpong-svc
          port: 5000
