apiVersion: v1
kind: Service
metadata:
  name: hashgenerator-svc
spec:
  type: ClusterIP
  selector:
    app: hashgenerator
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
