apiVersion: v1
kind: Service
metadata:
  name: hashgenerator-svc-1
  namespace: exercises
spec:
  type: LoadBalancer
  selector:
    app: hashgenerator-1
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: hashgenerator-svc-2
  namespace: exercises
spec:
  type: LoadBalancer
  selector:
    app: hashgenerator-2
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
