apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-dep
  template:
    metadata:
      labels:
        app: todo-dep
    spec:
      volumes:
        - name: the-project-pvc
          persistentVolumeClaim:
            claimName: the-project-pvc
      containers:
        - name: todo-dep
          image: todo:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 5000
          volumeMounts:
            - name: the-project-pvc
              mountPath: /data
