apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-dep
  template:
    metadata:
      labels:
        app: todo-dep
    spec:
      containers:
        - name: todo-dep
          image: todo:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 5000
