apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-dep
  template:
    metadata:
      labels:
        app: todo-dep
    spec:
      containers:
        - name: todo-dep
          image: saakbar/todo-app:latest
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "5000"
          - name: BACKEND_HOST
            value: "todo-backend-svc:5001"
          ports:
          - containerPort: 5000
