apiVersion: v1
kind: Service
metadata:
  name: todo-svc
  namespace: project
spec:
  type: LoadBalancer
  selector:
    app: todo-dep
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
