apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-log-output

resources:
- ./../../base

namePrefix: staging-

images:
- name: log-output-image
  newName: saakbar/log_output
  newTag: v1.0.0
