apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployments.yaml
  - manifests/service.yaml

images:
  - name: todo-app-image
    newName: saakbar/todo-app
    newTag: v1