name: Build and publish application

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GIT_ACTIONS_SECRET }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish backend
        run: |-
          cd log_output/
          docker build --tag "saakbar/log_output:v${{ steps.release.outputs.version }}" -f Dockerfile .
          docker push "saakbar/log_output:v${{ steps.release.outputs.version }}"
          cd ..
          cd the_project/
          docker build --tag "saakbar/todo-app:v${{ steps.release.outputs.version }}" -f todo-app/Dockerfile todo-app
          docker push "saakbar/todo-app:v${{ steps.release.outputs.version }}"
          docker build --tag "saakbar/todo-backend:v${{ steps.release.outputs.version }}" -f todo-backend/Dockerfile todo-backend
          docker push "saakbar/todo-app:v${{ steps.release.outputs.version }}"
          docker build --tag "saakbar/broadcaster:v${{ steps.release.outputs.version }}" -f broadcaster/Dockerfile broadcaster
          docker push "saakbar/todo-app:v${{ steps.release.outputs.version }}"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |-
          cd log_output/
          kustomize edit set image log-output-image=saakbar/log_output:v${{ steps.release.outputs.version }}
          cd ..
          cd the_project/
          kustomize edit set image todo-app-image=saakbar/todo-app:v${{ steps.release.outputs.version }}
          kustomize edit set image todo-backend-image=saakbar/todo-backend:v${{ steps.release.outputs.version }}
          kustomize edit set image broadcaster-image=saakbar/broadcaster:v${{ steps.release.outputs.version }}
    
      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'the_project/kustomization.yaml log_output/kustomization.yaml'
          message: New version released v${{ steps.release.outputs.version }}
