name: Build and publish application

on:
  push:
    branches:
      - main

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish backend
        run: |-
          cd log_output/
          docker build --tag "saakbar/log_output:$GITHUB_SHA" -f Dockerfile .
          docker push "saakbar/log_output:$GITHUB_SHA"
          cd ..
          cd the_project/
          docker build --tag "saakbar/todo-app:$GITHUB_SHA" -f todo-app/Dockerfile todo-app
          docker push "saakbar/todo-app:$GITHUB_SHA"
          docker build --tag "saakbar/todo-backend:$GITHUB_SHA" -f todo-backend/Dockerfile todo-backend
          docker push "saakbar/todo-app:$GITHUB_SHA"
          docker build --tag "saakbar/broadcaster:$GITHUB_SHA" -f broadcaster/Dockerfile broadcaster
          docker push "saakbar/todo-app:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |-
          cd log_output/
          kustomize edit set image log-output-image=saakbar/log_output:$GITHUB
          cd ..
          cd the_project/
          kustomize edit set image todo-app-image=saakbar/todo-app:$GITHUB_SHA
          kustomize edit set image todo-backend-image=saakbar/todo-backend:$GITHUB_SHA
          kustomize edit set image broadcaster-image=saakbar/broadcaster:$GITHUB_SHA
    
      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'the_project/kustomization.yaml log_output/kustomization.yaml'
          message: New version released ${{ github.sha }}
