name: Deploy to GKE with Kustomize

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: dwk-environments

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Build Docker image
      run: |
        APP_IMAGE="europe-north1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/shujaakbar/app:${GITHUB_SHA}"
        BACKEND_IMAGE="europe-north1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/shujaakbar/backend:${GITHUB_SHA}"
        docker build -t $APP_IMAGE -f the_project/todo-app/Dockerfile the_project/todo-app/
        docker build -t $BACKEND_IMAGE -f the_project/todo-backend/Dockerfile the_project/todo-backend/
        echo "APP_IMAGE=$APP_IMAGE" >> $GITHUB_ENV
        echo "BACKEND_IMAGE=$BACKEND_IMAGE" >> $GITHUB_ENV

    - name: Push Docker Image
      run: |
        docker push $APP_IMAGE
        docker push $BACKEND_IMAGE

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        cd the_project/ 
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Update image in Kustomize overlay
      run: |
        ./kustomize edit set image todo-app-image=$APP_IMAGE
        ./kustomize edit set image todo-backend-image=$BACKEND_IMAGE

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl apply -k .
