name: Deploy to GKE with Kustomize

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    environment: dwk-environments
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker europe-north1-docker.pkg.dev

    - name: Build Docker image
      run: |
        APP_IMAGE="europe-north1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/shujaakbar/app:${GITHUB_SHA}"
        BACKEND_IMAGE="europe-north1-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/shujaakbar/backend:${GITHUB_SHA}"
        docker build -t $APP_IMAGE -f the_project/todo-app/Dockerfile the_project/todo-app/
        docker build -t $BACKEND_IMAGE -f the_project/todo-backend/Dockerfile the_project/todo-backend/
        echo "APP_IMAGE=$APP_IMAGE" >> $GITHUB_ENV
        echo "BACKEND_IMAGE=$BACKEND_IMAGE" >> $GITHUB_ENV

    - name: Push Docker Image
      run: |
        docker push $APP_IMAGE
        docker push $BACKEND_IMAGE

    - name: Disable GKE Auth Plugin
      run: |
        gcloud config set container/use_application_default_credentials false
        gcloud config set container/use_v1_api true

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials \
          ${{ secrets.GKE_CLUSTER }} \
          --zone ${{ secrets.GKE_ZONE }} \
          --project ${{ secrets.GKE_PROJECT }}

    - name: Update image in Kustomize overlay
      run: |
        cd the_project/
        kustomize edit set image todo-app-image=$APP_IMAGE
        kustomize edit set image todo-backend-image=$BACKEND_IMAGE

    - name: Apply Kustomize to GKE
      env:
        USE_GKE_GCLOUD_AUTH_PLUGIN: "False"
      run: |
        cd the_project/
        kubectl apply -k .
